# Generated by Django 5.1.6 on 2025-04-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_initial_document_types'),
        ('loan', '0012_loanapplication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanapplication')),
                ('required_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.requireddocument')),
            ],
        ),
    ]
