# Generated by Django 5.1.6 on 2025-04-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Agent'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=10),
        ),
    ]
