# Generated by Django 5.1.6 on 2025-04-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
