# Generated by Django 5.1.6 on 2025-04-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/loan_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_points', to='loan.loanscheme')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='loan.loanscheme')),
            ],
        ),
        migrations.CreateModel(
            name='CoveredSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_sectors', to='loan.loanscheme')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='loan.loanscheme')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='loan.loanscheme')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to='loan.loanscheme')),
            ],
        ),
    ]
