# Generated by Django 5.1.6 on 2025-04-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanscheme',
            old_name='short_name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='loanscheme',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanscheme',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
