# Generated by Django 5.1.6 on 2025-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loanapplication_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
