# Generated by Django 5.1.6 on 2025-04-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loanapplication_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
