# Generated by Django 5.1.6 on 2025-04-18 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_alter_loanapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone Number'), ('date', 'Date'), ('file', 'File Upload'), ('address', 'Address'), ('select', 'Select Options'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for select/radio/checkbox fields', null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_data_fields', to='loan.loanscheme')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
