# Generated by Django 5.1.6 on 2025-04-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_requireddatafield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequiredDocument',
        ),
    ]
