# Generated by Django 5.1.6 on 2025-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_loanapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_application_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='report',
            field=models.FileField(blank=True, help_text='Upload PDF report', null=True, upload_to='loan_reports/%Y/%m/%d/'),
        ),
    ]
