# Generated by Django 5.1.6 on 2025-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_loanapplication_loan_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('not_converted', 'Not Converted'), ('assigned', 'Assigned'), ('details_collected', 'Details Collected'), ('document_collected', 'Document Collected'), ('form_filled', 'Form Filled'), ('under_review', 'Under Review'), ('closed', 'Closed'), ('dropped', 'Dropped')], default='new_lead', max_length=20),
        ),
    ]
